#!/usr/bin/env bash

## Power Menu for dwl

# Import Current Theme
DIR="$HOME/.config/dwl/scripts"
RASI="$DIR/sleek-dark.rasi"

# Theme Elements
prompt="`hostname`"
mesg="Uptime : `uptime -p | sed -e 's/up //g'`"

# Options
option_1=" Lock"
option_2=" Logout"
option_3=" Suspend"
option_4=" Hibernate"
option_5=" Reboot"
option_6="⏻ Shutdown"

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Confirmation CMD
confirm_cmd() {
	rofi -dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-theme ${RASI}
}

# Ask for confirmation
confirm_exit() {
	echo -e " Yes\n No" | confirm_cmd
}

# Confirm and execute
confirm_run () {
	selected="$(confirm_exit)"
	if [[ "$selected" == " Yes" ]]; then
        ${1} && ${2} && ${3} && ${4}
    else
        exit
    fi
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		# Lock screen (using swaylock or similar)
		swaylock || loginctl lock-session
	elif [[ "$1" == '--opt2' ]]; then
		# Logout from dwl
		confirm_run 'pkill dwl'
	elif [[ "$1" == '--opt3' ]]; then
		# Suspend
		confirm_run 'systemctl suspend'
	elif [[ "$1" == '--opt4' ]]; then
		# Hibernate
		confirm_run 'systemctl hibernate'
	elif [[ "$1" == '--opt5' ]]; then
		# Reboot
		confirm_run 'systemctl reboot'
	elif [[ "$1" == '--opt6' ]]; then
		# Shutdown
		confirm_run 'systemctl poweroff'
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    "$option_1")
		run_cmd --opt1
        ;;
    "$option_2")
		run_cmd --opt2
        ;;
    "$option_3")
		run_cmd --opt3
        ;;
    "$option_4")
		run_cmd --opt4
        ;;
    "$option_5")
		run_cmd --opt5
        ;;
    "$option_6")
		run_cmd --opt6
        ;;
esac
